package:
  name: {{ environ.get('ANACONDA_PACKAGE')|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION')|string|replace('-', '.') }}

{% set version = environ.get('COMMIT_TAG', None) or environ.get('COMMIT_LATEST_TAG', None) or None %}
{% set sha256 = {
    "2024.09.16": "0c093eff288dbb3c3ad2b04b0657e47e31a7db10c2bb56f879394b016884512a"
} %}

{% set version = version or sha256.keys()|first %}
source:
  url: "https://lhapdf.hepforge.org/downloads/?f=LHAPDF-{{ version }}.tar.gz"
  {% if sha256.get(version, None) %}
  sha256: {{ sha256.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler
    
    - cmake                        # Build system
    - make                         # Make utility
    - xorg-imake                   # X.Org imake utility
    - xorg-libx11                  # X11 client-side library
    - xorg-libxaw                  # Xaw widget set for X11
    - freetype                     # FreeType library for font rendering
    - openmotif-dev                # Open Motif development libraries
    - libgcc-ng                    # GNU C Compiler support library
    - libstdcxx-ng                 # GNU Standard C++ Library
    - zlib                         # Compression library (if needed)

  host:
    - python
    - pip
    - setuptools

  run:
    - python

about:
  home: "https://cernlib.web.cern.ch"
  license: "GPL-3.0"
  summary: "CERN library for high-energy physics calculations."
  description: |
    CERNLIB is a collection of general-purpose libraries and modules maintained and developed by CERN for physics data analysis and related purposes.

extra:
  recipe-maintainers:
    - meiyasan

