{% set name = "cernlib" %}
{% set version = environ.get('COMMIT_TAG', environ.get('COMMIT_LATEST_TAG', "0.0.0")+"-dev")|string|replace('-', '.')  %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://cernlib.web.cern.ch/download/2024_source/tar/cernlib-cernlib-2024.09.16.0-free.tar.gz"

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - python
    - pip
    - setuptools

  run:
    - python

about:
  home: "https://cernlib.web.cern.ch"
  license: "GPL-3.0"
  summary: "CERN library for high-energy physics calculations."
  description: |
    CERNLIB is a collection of general-purpose libraries and modules maintained and developed by CERN for physics data analysis and related purposes.

extra:
  recipe-maintainers:
    - meiyasan

