{% set name = "cernlib" %}
{% set version = environ.get('GITHUB_REF_NAME', 'untagged')|string|replace('-', '_') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://cernlib.web.cern.ch/download/2024_source/tar/cernlib-cernlib-2024.09.16.0-free.tar.gz"
  sha256: "db111e67d895507e245cdb285086cd5f5529b4f5a1b5794a7ef5753bbb582201"

requirements:
  build:
    - cmake
    - make
    - gcc_impl_linux-64
    - gxx_impl_linux-64
  host:
    - libgcc-ng
  run:
    - libgcc-ng
    - libcxx

about:
  home: "https://cernlib.web.cern.ch"
  license: "GPL-3.0"
  summary: "CERN library for high-energy physics calculations."
  description: |
    CERNLIB is a collection of general-purpose libraries and modules maintained and developed by CERN for physics data analysis and related purposes.

extra:
  recipe-maintainers:
    - meiyasan

