{% set name = environ.get('ANACONDA_PACKAGE')|string %}
{% set version = environ.get('ANACONDA_VERSION', "2024.09.16")|string|replace('-', '.') %}
{% set sha256 = {
    "2024.09.16": "db111e67d895507e245cdb285086cd5f5529b4f5a1b5794a7ef5753bbb582201"
} %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://cernlib.web.cern.ch/download/2024_source/tar/cernlib-cernlib-{{ version }}-free.tar.gz"
  sha256: {{ sha256.get(version, "?") }}

requirements:
  build:
    - {{ compiler('gfortran') }}<11.3 # GNU Fortran compiler
    - {{ compiler('c') }}<11.3        # GNU C compiler
    - {{ compiler('cxx') }}<11.3      # GNU C++ compiler
    
    - cmake=3.18                   # Build system
    - make                         # Make utility
    - xorg-imake                   # X.Org imake utility
    - xorg-libx11                  # X11 client-side library
    - xorg-libxaw                  # Xaw widget set for X11
    - freetype                     # FreeType library for font rendering
    - openmotif-dev                # Open Motif development libraries
    - libgcc-ng                    # GNU C Compiler support library
    - libstdcxx-ng                 # GNU Standard C++ Library
    - zlib                         # Compression library (if needed)

  host:
    - python
    - pip
    - setuptools

  run:
    - python

about:
  home: "https://cernlib.web.cern.ch"
  license: "GPL-3.0"
  summary: "CERN library for high-energy physics calculations."
  description: |
    CERNLIB is a collection of general-purpose libraries and modules maintained and developed by CERN for physics data analysis and related purposes.

extra:
  recipe-maintainers:
    - meiyasan

