{% set name = environ.get('ANACONDA_PACKAGE')|string %}
{% set version = environ.get('ANACONDA_VERSION')|string|replace('-', '.')  %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://cernlib.web.cern.ch/download/2024_source/tar/cernlib-cernlib-2024.09.16.0.tar.gz"

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

    - cmake
    - make
    - xorg-imake
    - xorg-libx11
    - freetype
    - openmotif

  host:
    - python
    - pip
    - setuptools

  run:
    - python

about:
  home: "https://cernlib.web.cern.ch"
  license: "GPL-3.0"
  summary: "CERN library for high-energy physics calculations."
  description: |
    CERNLIB is a collection of general-purpose libraries and modules maintained and developed by CERN for physics data analysis and related purposes.

extra:
  recipe-maintainers:
    - meiyasan

