name: Conda Build

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Install Anaconda Client
        run: |
          conda install -c conda-forge -y conda-smithy conda-verify anaconda-client
          
      - name: Rerender Feedstock
        run: conda smithy rerender

      - name: Build Package
        run: conda build . --output-folder pkgs

      - name: Upload to Anaconda
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          /usr/share/miniconda/bin/anaconda upload --user hep-forge pkgs/*/*.tar.bz2
          for pkg in pkgs/*/*.tar.bz2; do
              /usr/share/miniconda/bin/anaconda upload --user hep-forge "$pkg"
          done
