name: Conda Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          tags: true

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_TAG="$(git describe --tags --abbrev=0 | awk '{print $2}')" 
          COMMIT_BRANCH=$(git branch --contains "$COMMIT_SHA")
          echo "$COMMIT_SHA $COMMIT_TAG $COMMIT_BRANCH"
