name: Conda Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "Commit SHA: $COMMIT_SHA"
          echo "Branch Name: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit Message: $(git log -1 --pretty=%B)"
          echo "Associated Tags: $(git tag --points-at $COMMIT_SHA)"
