name: Conda Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          tags: true

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "Commit SHA: $COMMIT_SHA"
          echo "$(git branch --contains "$COMMIT_SHA" | grep -v 'HEAD' | awk 'NR==1')"
          echo "$(git show-ref --tags -d)"
          echo "Associated Tags: $(git describe --tags --abbrev=0)"
