name: Conda Build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Test
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Branch name is: $BRANCH_NAME"
          echo "Headref name is: ${{ github.head_ref }}"
          echo "refname is: ${{ github.ref_name }}"
          git branch
          # Get the commit SHA of the tag
          commit_sha=$(git rev-list -n 1 $BRANCH_NAME)
          git branch --contains $commit_sha
          echo ":::: $(git rev-parse --abbrev-ref HEAD)"
          echo ":::: $(git branch)"

